import type { LibProperties } from './libProperties';
import { exposeLib } from 'hel-lib-proxy';
import { LIB_NAME } from 'configs/subApp';

export const lib = exposeLib<LibProperties>(LIB_NAME);

// 以下单个导出，支持 import { Button } from 'hel-antd'; 直接解构的语法
export const Affix = lib.Affix;
export const Alert = lib.Alert;
export const Anchor = lib.Anchor;
export const AutoComplete = lib.AutoComplete;
export const Avatar = lib.Avatar;
export const BackTop = lib.BackTop;
export const Badge = lib.Badge;
export const Breadcrumb = lib.Breadcrumb;
export const Button = lib.Button;
export const Calendar = lib.Calendar;
export const Card = lib.Card;
export const Carousel = lib.Carousel;
export const Cascader = lib.Cascader;
export const Checkbox = lib.Checkbox;
export const Col = lib.Col;
export const Collapse = lib.Collapse;
export const Comment = lib.Comment;
export const ConfigProvider = lib.ConfigProvider;
export const DatePicker = lib.DatePicker;
export const Descriptions = lib.Descriptions;
export const Divider = lib.Divider;
export const Drawer = lib.Drawer;
export const Dropdown = lib.Dropdown;
export const Empty = lib.Empty;
export const Form = lib.Form;
export const Grid = lib.Grid;
export const Image = lib.Image;
export const Input = lib.Input;
export const InputNumber = lib.InputNumber;
export const Layout = lib.Layout;
export const List = lib.List;
export const Mentions = lib.Mentions;
export const Menu = lib.Menu;
export const Modal = lib.Modal;
export const message = lib.message;
export const notification = lib.notification;
export const PageHeader = lib.PageHeader;
export const Pagination = lib.Pagination;
export const Popconfirm = lib.Popconfirm;
export const Popover = lib.Popover;
export const Progress = lib.Progress;
export const Radio = lib.Radio;
export const Rate = lib.Rate;
export const Result = lib.Result;
export const Row = lib.Row;
export const Segmented = lib.Segmented;
export const Select = lib.Select;
export const Skeleton = lib.Skeleton;
export const Slider = lib.Slider;
export const Space = lib.Space;
export const Spin = lib.Spin;
export const Statistic = lib.Statistic;
export const SegStepsmented = lib.Steps;
export const Switch = lib.Switch;
export const Table = lib.Table;
export const Tabs = lib.Tabs;
export const Tag = lib.Tag;
export const TestExport = lib.TestExport;
export const TimePicker = lib.TimePicker;
export const Timeline = lib.Timeline;
export const Tooltip = lib.Tooltip;
export const Transfer = lib.Transfer;
export const Tree = lib.Tree;
export const TreeSelect = lib.TreeSelect;
export const Typography = lib.Typography;
export const theme = lib.theme;
export const Upload = lib.Upload;
export const version = lib.version;

// 模块类型导出，方便懒加载时透传给 preFetchLib<Lib>('remote-tedsign-react') 用
export type Lib = LibProperties;

export default lib;
